### ISSUE TITLE
map indicator problem

### ISSUE THREAD

**Issue by lxymyy** [chanchanchan97/ICAFusion#20]
Hello, I tried to get the map indicator on the FLIR data set in your paper, but I ended up getting map50 as 0.81, but map0.5:0.95 as 0.39, which is a little different from your indicator.

**Comment by chanchanchan97** [comment]
Sorry, we continuously optimize our codes, resulting in some difference from the experimental results in the paper. However, the codes of module for multimodal feature fusion remains consistent with the methods proposed in this paper.

**Comment by lxymyy** [comment]
thank you for your reply，When training the FLIR data set, which ymal file did you use? Is it yolov5l_Transfusion_FLIR.yaml, yolov5l_NiNfusion_FLIR.yaml or yolov5l_Add_FLIR.yaml?

**Comment by chanchanchan97** [comment]
> thank you for your reply，When training the FLIR data set, which ymal file did you use? Is it yolov5l_Transfusion_FLIR.yaml, yolov5l_NiNfusion_FLIR.yaml or yolov5l_Add_FLIR.yaml?

yolov5l_Transfusion_FLIR.yaml

**Comment by Clustering1** [comment]
您好，可以请教一下怎么跑出来相关的指标嘛，我运行test.py之后显示的是这种
![测试结果](https://github.com/chanchanchan97/ICAFusion/assets/94001504/7447919e-8d93-43ac-9c1a-9ef774b71aa1)

**Comment by Clustering1** [comment]
这是我的邮箱：CZsjly0614@163.com，非常需要您的相关指导！
